name: vprofile-actions

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java (needed for Maven + Sonar Scanner)
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      - name: Run Maven tests
        run: mvn -B test

      - name: Run Checkstyle
        run: mvn -B checkstyle:check

      # Setup SonarQube Scanner
      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      # Run SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes

      # Quality Gate
      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

  # build_and_publish:
  #   needs: testing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Upload image to ECR
  #       uses: appleboy/docker-ecr-action@master
  #       with:
  #         access_key: ${{ secrets.aws_access_key_id }}
  #         secret_key: ${{ secrets.aws_secret_access_key }}
  #         registry: ${{ secrets.registry }}
  #         cache_from: ${{ secrets.cache }}
  #         repo: ${{ env.ECR_REPOSITORY }}
  #         region: ${{ env.AWS_REGION }}
  #         tags: latest,${{ github.run_number }}
  #         daemon_off: false
  #         dockerfile: ./Dockerfile
  #         context: ./
